baseURL = "https://glimpse-editor.org"
languageCode = "en-us"
title = "Glimpse"
theme = "glimpse"
SectionPagesMenu = "main"
rssLimit = 20

[params]
  custom_css = ["css/glimpse.css"]
  favicon = "favicon"
  featuredImg = "kelly-sikkema-SGl7ntWLUkw-unsplash.jpg"
  projectName = "Glimpse Image Editor"
  logo = "logo_hex_full_invert.svg"
  tagline = "A Photo Editor For Everyone"
